In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('drug.csv')

In [3]:
data.head()
data.describe()
data.count()

Age            200
Sex            200
BP             200
Cholesterol    200
Na_to_K        200
Drug           200
dtype: int64

## categorized

In [4]:
data.head()# Sex,Cholesterol and drug categorized

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [5]:
age = data.iloc[:,0:1].values
sex = data.iloc[:,1:2].values
bp = data.iloc[:,2:3].values
chol = data.iloc[:,3:4].values
natok = data.iloc[:,4:5].values
drug = data.iloc[:,5].values

In [6]:
ohe = preprocessing.OneHotEncoder()
Sex = ohe.fit_transform(sex).toarray()

In [7]:
print(Sex)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 

In [8]:
Bp = ohe.fit_transform(bp).toarray()

In [9]:
print(Bp)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1.

In [10]:
Chol = ohe.fit_transform(chol).toarray()

In [11]:
print(Chol[110])

[1. 0.]


In [12]:
sonuc = pd.DataFrame(data = age,index= range(200),columns=['Age'])

In [13]:
sonuc1 = pd.DataFrame(data = Sex,index= range(200),columns=['F','M'])

In [14]:
sonuc2 = pd.DataFrame(data = Bp,index= range(200),columns=['BpHigh','BpNormal','BpLow'])

In [15]:
sonuc3 = pd.DataFrame(data = Chol,index= range(200),columns=['CholHigh','CholLow'])

In [16]:
sonuc4 = pd.DataFrame(data = natok,index= range(200),columns=['Na_to_k'])

In [17]:
t = pd.concat([sonuc,sonuc1],axis=1)
print(t)

     Age    F    M
0     23  1.0  0.0
1     47  0.0  1.0
2     47  0.0  1.0
3     28  1.0  0.0
4     61  1.0  0.0
..   ...  ...  ...
195   56  1.0  0.0
196   16  0.0  1.0
197   52  0.0  1.0
198   23  0.0  1.0
199   40  1.0  0.0

[200 rows x 3 columns]


In [18]:
t1 = pd.concat([t,sonuc2],axis=1)
print(t1)

     Age    F    M  BpHigh  BpNormal  BpLow
0     23  1.0  0.0     1.0       0.0    0.0
1     47  0.0  1.0     0.0       1.0    0.0
2     47  0.0  1.0     0.0       1.0    0.0
3     28  1.0  0.0     0.0       0.0    1.0
4     61  1.0  0.0     0.0       1.0    0.0
..   ...  ...  ...     ...       ...    ...
195   56  1.0  0.0     0.0       1.0    0.0
196   16  0.0  1.0     0.0       1.0    0.0
197   52  0.0  1.0     0.0       0.0    1.0
198   23  0.0  1.0     0.0       0.0    1.0
199   40  1.0  0.0     0.0       1.0    0.0

[200 rows x 6 columns]


In [19]:
t2 = pd.concat([t1,sonuc3],axis=1)
print(t2)

     Age    F    M  BpHigh  BpNormal  BpLow  CholHigh  CholLow
0     23  1.0  0.0     1.0       0.0    0.0       1.0      0.0
1     47  0.0  1.0     0.0       1.0    0.0       1.0      0.0
2     47  0.0  1.0     0.0       1.0    0.0       1.0      0.0
3     28  1.0  0.0     0.0       0.0    1.0       1.0      0.0
4     61  1.0  0.0     0.0       1.0    0.0       1.0      0.0
..   ...  ...  ...     ...       ...    ...       ...      ...
195   56  1.0  0.0     0.0       1.0    0.0       1.0      0.0
196   16  0.0  1.0     0.0       1.0    0.0       1.0      0.0
197   52  0.0  1.0     0.0       0.0    1.0       1.0      0.0
198   23  0.0  1.0     0.0       0.0    1.0       0.0      1.0
199   40  1.0  0.0     0.0       1.0    0.0       0.0      1.0

[200 rows x 8 columns]


In [20]:
t3 = pd.concat([t2,sonuc4],axis=1)
print(t3)

     Age    F    M  BpHigh  BpNormal  BpLow  CholHigh  CholLow  Na_to_k
0     23  1.0  0.0     1.0       0.0    0.0       1.0      0.0   25.355
1     47  0.0  1.0     0.0       1.0    0.0       1.0      0.0   13.093
2     47  0.0  1.0     0.0       1.0    0.0       1.0      0.0   10.114
3     28  1.0  0.0     0.0       0.0    1.0       1.0      0.0    7.798
4     61  1.0  0.0     0.0       1.0    0.0       1.0      0.0   18.043
..   ...  ...  ...     ...       ...    ...       ...      ...      ...
195   56  1.0  0.0     0.0       1.0    0.0       1.0      0.0   11.567
196   16  0.0  1.0     0.0       1.0    0.0       1.0      0.0   12.006
197   52  0.0  1.0     0.0       0.0    1.0       1.0      0.0    9.894
198   23  0.0  1.0     0.0       0.0    1.0       0.0      1.0   14.020
199   40  1.0  0.0     0.0       1.0    0.0       0.0      1.0   11.349

[200 rows x 9 columns]


In [21]:
x_train, x_test, y_train, y_test = train_test_split(t3,drug,test_size=0.40,random_state=0)

In [22]:
x_train,x_test

(     Age    F    M  BpHigh  BpNormal  BpLow  CholHigh  CholLow  Na_to_k
 187   47  0.0  1.0     1.0       0.0    0.0       1.0      0.0   10.403
 46    37  1.0  0.0     1.0       0.0    0.0       1.0      0.0   13.091
 138   51  0.0  1.0     1.0       0.0    0.0       0.0      1.0   11.343
 195   56  1.0  0.0     0.0       1.0    0.0       1.0      0.0   11.567
 108   72  0.0  1.0     1.0       0.0    0.0       0.0      1.0    9.677
 ..   ...  ...  ...     ...       ...    ...       ...      ...      ...
 67    17  0.0  1.0     0.0       0.0    1.0       0.0      1.0   10.832
 192   72  0.0  1.0     0.0       1.0    0.0       1.0      0.0   16.310
 117   40  1.0  0.0     0.0       0.0    1.0       1.0      0.0   10.103
 47    68  0.0  1.0     0.0       1.0    0.0       1.0      0.0   10.291
 172   39  1.0  0.0     0.0       0.0    1.0       0.0      1.0   17.225
 
 [120 rows x 9 columns],
      Age    F    M  BpHigh  BpNormal  BpLow  CholHigh  CholLow  Na_to_k
 18    23  0.0  1.0     

# Classification

In [87]:
sc = StandardScaler()
X_train = sc.fit_transform(x_train)

# Logistic Regression

In [88]:
loreg = LogisticRegression(random_state=0)
loreg.fit(X_train,y_train)
y_pred = loreg.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(y_pred)

[[30  0  9  0  0]
 [ 3  0  5  0  0]
 [ 0  0  4  0  0]
 [ 2  0  2  0  0]
 [ 8  0 17  0  0]]
['drugB' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugB' 'DrugY'
 'drugB' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugB' 'drugB' 'DrugY' 'drugB'
 'DrugY' 'DrugY' 'DrugY' 'drugB' 'drugB' 'DrugY' 'DrugY' 'DrugY' 'drugB'
 'DrugY' 'DrugY' 'drugB' 'drugB' 'DrugY' 'drugB' 'drugB' 'DrugY' 'drugB'
 'drugB' 'drugB' 'drugB' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugB' 'DrugY'
 'drugB' 'drugB' 'DrugY' 'drugB' 'drugB' 'DrugY' 'drugB' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugB' 'drugB' 'DrugY' 'DrugY' 'drugB'
 'DrugY' 'drugB' 'DrugY' 'drugB' 'DrugY' 'drugB' 'drugB' 'drugB' 'drugB'
 'DrugY' 'drugB' 'drugB' 'drugB' 'DrugY' 'drugB' 'drugB' 'DrugY']


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


# KNN

In [89]:
knn = KNeighborsClassifier(n_neighbors=20,metric='manhattan')
knn.fit(X_train,y_train)
y_pred = knn.predict(x_test)
cm2 = confusion_matrix(y_test,y_pred)
print(cm2)
print(y_pred)

[[39  0  0  0  0]
 [ 8  0  0  0  0]
 [ 4  0  0  0  0]
 [ 4  0  0  0  0]
 [25  0  0  0  0]]
['DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY']


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


# Naive Bayes

In [90]:
nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred = nb.predict(x_test)
cm3 = confusion_matrix(y_test,y_pred)
print(cm3)
print(y_pred)

[[39  0  0  0  0]
 [ 8  0  0  0  0]
 [ 4  0  0  0  0]
 [ 4  0  0  0  0]
 [25  0  0  0  0]]
['DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY']


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


# SVC

In [91]:
sv = SVC(kernel='poly')
sv.fit(X_train,y_train)
y_pred = sv.predict(x_test)
cm4 = confusion_matrix(y_test,y_pred)
print(cm4)
print(y_pred)

[[39  0  0  0  0]
 [ 7  0  1  0  0]
 [ 2  0  2  0  0]
 [ 4  0  0  0  0]
 [17  0  8  0  0]]
['DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'drugB' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'drugB' 'drugB' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'drugB' 'DrugY' 'drugB' 'drugB' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'drugB' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugB' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'drugB' 'DrugY' 'drugB' 'DrugY' 'drugB' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY']


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


# Decision Tree

In [92]:
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(X_train,y_train)
y_pred = dt.predict(x_test)
cm5 = confusion_matrix(y_test,y_pred)
print(cm5)
print(y_pred)

[[39  0  0  0  0]
 [ 8  0  0  0  0]
 [ 4  0  0  0  0]
 [ 4  0  0  0  0]
 [25  0  0  0  0]]
['DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY']


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


# Random Forest

In [93]:
rf = RandomForestClassifier(random_state=0,criterion='entropy')
rf.fit(X_train,y_train)
y_pred = dt.predict(x_test)
cm6 = confusion_matrix(y_test,y_pred)
print(cm6)
print(y_pred)

[[39  0  0  0  0]
 [ 8  0  0  0  0]
 [ 4  0  0  0  0]
 [ 4  0  0  0  0]
 [25  0  0  0  0]]
['DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY']


C:\Users\asus\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(
